base:
  project_name: "crm-mlops"
  random_state: 42
  test_size: 0.2

data_ingestion:
  drive_file_id: "1K_yDMbacLq6hUsxUHfgFDazGFF967cC6"
  local_data_path: "data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  unzip_dir: "data/raw"

model_trainer:
  model_name: "xgboost"
  output_path: "models/churn_model.onnx"
  n_trials: 50
  cv: 3

data_transformation:
  root_dir: "data/processed"
  data_path: "data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  preprocessor_obj_file_path: "models/preprocessor.pkl"
